# TestingEngine.ThrowIfBugFound method

Throws either an AssertionFailureException, if a bug was found, or an unhandled Exception, if one was thrown.

```csharp
public void ThrowIfBugFound()
```

## See Also

* class [TestingEngine](../TestingEngine.md)
* namespace [Microsoft.Coyote.SystematicTesting](../TestingEngine.md)
* assembly [Microsoft.Coyote.Test](../../Microsoft.Coyote.Test.md)

<!-- DO NOT EDIT: generated by xmldocmd for Microsoft.Coyote.Test.dll -->
